server:
  port: 1975
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/training
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
    show-sql: true
